sonar.verbose=true
sonar.organization=sai-training	
sonar.projectKey=sai-training-key_saidemytrend
sonar.projectName=saidemytrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
